name: hello-worldAdd commentMore actions

on:
  workflow_call: # This makes the workflow reusable
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Deploy Hello World!"